### ISSUE TITLE
Refactor code to use lisc package

### ISSUE THREAD

**Issue by bcipolli** [ERPscanr/ERP_SCANR#2]
README and [LISC projects page](https://github.com/lisc-tools/Projects) seem to indicate that this code is leveraging `lisc`. In checking the code here, I am not sure that it is:
https://github.com/TomDonoghue/ERP_SCANR/blob/master/erpsc/count.py
https://github.com/TomDonoghue/ERP_SCANR/blob/master/erpsc/words.py

Would be great to refactor this code to leverage lisc, if so. Apologies if I've misunderstood!

**Comment by TomDonoghue** [comment]
I should probably be a bit more clear that listed LISC projects are LISC or it's pre-cursors / equivalents. You are right that ERPSCANR doesn't technically use LISC. 

ERPSCANR actually came first, I wrote the code, somewhat overly tuned to the topic, and then at a later date made LISC as a generalized version. It's on the ToDo to refactor ERPSCANR to use LISC, though relatively low-priority, since in the grand scheme of themes, they are more-or-less the same code (refactoring, as it is, wouldn't add any new functionality), and I don't really need to use ERPSCANR anymore (other than running it again with a new-scrape to finish up the project). 

When I step through ERPSCANR, I might refactor then to use LISC, if I decide to extend and add some new stuff, but as it stands I might leave this with the legacy version.

**Comment by TomDonoghue** [comment]
done
